### ISSUE TITLE
Switch Indent Style to Allman

### ISSUE THREAD

**Issue by Crorem** [Crorem/ftc_app_5452#1]
I'd prefer Allman to be the indent style over the existing K&R.

**Comment by Sass-Meister** [comment]
1st, can you give more specification as to what you are talking about.
2nd, what does Android studio default to.
3rd, how do I change Android studio to do what you want us to do

**Comment by Crorem** [comment]
1. [Yes](https://en.wikipedia.org/wiki/Indent_style)
2. K&R
3. It should be under settings, we can do it tomorrow.
